"""Ariel Data Challenge preprocessing and feature engineering package."""

from ariel_ml.config import DatasetConfig, DeepModelConfig, FeatureConfig, ModelConfig, PreprocessConfig
from ariel_ml.dataset_builder import (
    ArielDatasetBuilder,
    FeatureBuildResult,
    align_features_and_targets,
)
from ariel_ml.deep_models import (
    AutoencoderMLPRegressor,
    CNN1DRegressor,
    GRURegressor,
    LSTMRegressor,
    TCNRegressor,
    TorchSequenceRegressor,
    TransformerSequenceRegressor,
)
from ariel_ml.features import ArielFeatureBuilder
from ariel_ml.metrics import SigmaCalibrator, gaussian_nll, rmse_per_target
from ariel_ml.models import (
    BayesianRidgePCARegressor,
    BoostingPCARegressor,
    ExtraTreesPCARegressor,
    KernelRidgePCARegressor,
    LightGBMPCARegressor,
    ModelFactory,
    ModelPrediction,
    ResidualCorrectedRegressor,
    RidgePCARegressor,
    TargetPCARegressor,
    WeightedEnsembleRegressor,
    XGBoostPCARegressor,
)
from ariel_ml.pipeline import ArielPreprocessFeaturePipeline
from ariel_ml.preprocessing import (
    CalibrationBundle,
    CalibrationMetrics,
    DetectorCalibrator,
    LightCurveExtractor,
    LightCurves,
    LightCurveTransformer,
    TransitBoundaryDetector,
    TransitBounds,
)
from ariel_ml.submission import (
    SubmissionSchema,
    build_submission_frame,
    infer_submission_schema,
    predict_submission,
    save_submission,
)
from ariel_ml.training import (
    CrossValidationResult,
    EvaluationResult,
    HyperparameterSearchResult,
    SearchCandidateResult,
    TrainResult,
    cross_validate_model,
    evaluate_prediction,
    feature_dicts_to_frame,
    hyperparameter_search,
    refit_full_model,
    targets_to_matrix,
    train_model,
    train_model_on_indices,
)

__all__ = [
    "ArielFeatureBuilder",
    "ArielDatasetBuilder",
    "ArielPreprocessFeaturePipeline",
    "AutoencoderMLPRegressor",
    "BayesianRidgePCARegressor",
    "BoostingPCARegressor",
    "CalibrationBundle",
    "CalibrationMetrics",
    "CNN1DRegressor",
    "CrossValidationResult",
    "DatasetConfig",
    "DeepModelConfig",
    "DetectorCalibrator",
    "EvaluationResult",
    "ExtraTreesPCARegressor",
    "FeatureConfig",
    "FeatureBuildResult",
    "GRURegressor",
    "KernelRidgePCARegressor",
    "LSTMRegressor",
    "LightGBMPCARegressor",
    "LightCurveExtractor",
    "LightCurves",
    "LightCurveTransformer",
    "ModelConfig",
    "ModelFactory",
    "ModelPrediction",
    "PreprocessConfig",
    "RidgePCARegressor",
    "ResidualCorrectedRegressor",
    "SearchCandidateResult",
    "SigmaCalibrator",
    "SubmissionSchema",
    "TCNRegressor",
    "TargetPCARegressor",
    "TorchSequenceRegressor",
    "TrainResult",
    "HyperparameterSearchResult",
    "TransitBoundaryDetector",
    "TransitBounds",
    "TransformerSequenceRegressor",
    "WeightedEnsembleRegressor",
    "XGBoostPCARegressor",
    "align_features_and_targets",
    "build_submission_frame",
    "cross_validate_model",
    "evaluate_prediction",
    "feature_dicts_to_frame",
    "gaussian_nll",
    "hyperparameter_search",
    "infer_submission_schema",
    "predict_submission",
    "refit_full_model",
    "rmse_per_target",
    "save_submission",
    "targets_to_matrix",
    "train_model",
    "train_model_on_indices",
]
